# $Id: Makefile 74 2004-05-31 02:19:05Z knut.osmundsen@oracle.com $

#
# This is an example makefile.
#

TOOL = GCC
PROGRAMS = helloworld hello world
helloworld_SOURCES = hello.c
hello_SOURCES = hello.c
world_SOURCES = hello.c

DEPTH = ../../..
include $(DEPTH)/kBuild/rules.kMk

