# $Id: Makefile.kmk 683 2006-12-08 02:05:09Z knut.osmundsen@oracle.com $

SUBDIRS = lib gmake sed kDepPre kDepIDB
ifeq ($(BUILD_TARGET),win)
SUBDIRS += ash
endif

DEPTH = ..
include $(PATH_KBUILD)/rules.kmk

