# $Id: Makefile.kmk 1026 2007-06-04 01:30:19Z knut.osmundsen@oracle.com $

SUBDIRS = lib kmk sed kDepPre kDepIDB kObjCache
ifneq ($(BUILD_TARGET),win)
SUBDIRS += ash
endif

DEPTH = ..
include $(PATH_KBUILD)/rules.kmk

