# $Id: Makefile.kmk 716 2006-12-14 02:20:24Z knut.osmundsen@oracle.com $

SUBDIRS = lib gmake sed kDepPre kDepIDB
ifneq ($(BUILD_TARGET),win)
SUBDIRS += ash
endif

DEPTH = ..
include $(PATH_KBUILD)/rules.kmk

